/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.mit.csail.sdg.translator.A4Options;

public class AlloyTest {
    public static void main(String[] args) throws Exception {
        A4Options options = new A4Options();
    }
}
