/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AlloyTestTest{
    @Test public void appHasAGreeting() {
        AlloyTest classUnderTest = new AlloyTest();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
